spring:
  profiles:
    active: local

  batch:
    job:
      names: ${job.name:NONE}

---

spring:
  profiles: local
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:

---

spring:
  profiles: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: mhk
      password: mhk1234
